{
  "name": "watch-movies-backend",
  "version": "2.0.0",
  "builds": [
    {
      "type": "node",
      "builder": "node@18",
      "buildCommand": "npm install"
    }
  ],
  "startCommand": "node server/server.js",
  "env": [
    {
      "key": "NODE_ENV",
      "value": "production"
    }
  ]
}
